import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase";
import Login from "./Login.js";
import HomeComponent from "../Components/HomePage/HomeComponent";
export default function Home() {
  const [user, loading] = useAuthState(auth);

  return (
    <div className={styles.container}>
      <Head>
        <title>Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && "loading"}
      {!loading && user ? (
        <HomeComponent />
      ) : (
        !loading && <Login loading={loading} />
      )}
    </div>
  );
}
